---
# These are packages where the name is the same for the tested systems (see README).
- name: Install common package manager dependencies
  become: true
  # TODO: Consider pinning to particular versions.
  # TODO: Consider thinning scripts/dev_setup.sh and using that instead.
  ansible.builtin.package:
    name:
      - clang
      - curl
      - git
      - socat
      - lld
      - llvm
    state: present

- name: Install packages specific to Debian-like systems
  become: true
  ansible.builtin.package:
    name:
      - build-essential
      - libcap2-bin
      - libssl-dev
      - pkg-config
    state: present
  when: ansible_os_family == "Debian"

- name: Install packages specific to Redhat-like systems
  become: true
  ansible.builtin.package:
    name:
      - gcc
      - gcc-c++
      - kernel-devel
      - libcap
      - make
      - openssl-devel
      - pkgconfig
    state: present
  when: ansible_os_family == "Redhat"

- name: Install packages specific to Arch-like systems
  become: true
  ansible.builtin.package:
    name:
      - base-devel
      - libcap
      - openssl
      - pkgconf
    state: present
  when: ansible_os_family == "Archlinux"
