# This playbook downloads aptos-core and compiles the aptos-node binary.

---
- name: Make /opt if necessary
  become: true
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"

- name: Clone aptos-core repo
  ansible.builtin.git:
    repo: "https://github.com/aptos-labs/aptos-core.git"
    dest: "{{ vars.aptos_core_path }}"
    version: "{{ vars.git_rev }}"
    force: true

- name: Build aptos-node
  ansible.builtin.shell:
    cmd: >
      . $HOME/.cargo/env &&
      cd {{ vars.aptos_core_path }} &&
      cargo build --profile {{ vars.build_profile }} --package aptos-node
  tags:
    - skip_ansible_lint
