---
argument_specs:
  main:
    options:
      aptos_core_path:
        type: "str"
        description: "The absolute path where the role will clone aptos-core"

      build_profile:
        type: "str"
        description: "The profile to use for cargo build, e.g. release, performance, etc."

      git_rev:
        type: "str"
        required: true
        description: "The git rev to checkout, e.g. a branch name (devnet) or commit hash (e2c60c8ef)"
