# This playbook downloads aptos-core and compiles the Aptos binary,
# moving it into the configured location.

---
- hosts: nodes
  name: Build aptos-core binary
  vars:
    version: devnet
    aptos_core_path: /opt/aptos-core
    binary_path: /usr/bin/aptos-node
    build_profile: performance
  tasks:
    - name: Make /opt if necessary
      become: true
      ansible.builtin.file:
        path: /opt
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: "0755"

    - name: Clone aptos-core repo
      ansible.builtin.git:
        repo: 'https://github.com/aptos-labs/aptos-core.git'
        dest: "{{ vars.aptos_core_path }}"
        version: "{{ vars.version }}"

    - name: Build aptos-node
      ansible.builtin.shell:
        cmd: >
          . $HOME/.cargo/env &&
          cd {{ vars.aptos_core_path }} &&
          cargo build --profile performance --package aptos-node
      tags:
        - skip_ansible_lint

    - name: Copy aptos-node to {{ vars.binary_path }}
      ansible.builtin.copy:
        src: "{{ vars.aptos_core_path }}/target/{{ vars.build_profile }}/aptos-node"
        dest: "{{ vars.binary_path }}"
        mode: "0755"


