# This playbook sets up a fullnode that runs from source.

- name: Setup fullnode running from source
  hosts: nodes
  roles:
    - init_ansible
    - install_source_dependencies
    - build_binary
    - create_node_config
    - setup_firewall
    - setup_https
    - start_unit
